steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build','--scan']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t gcr.io/lavygradlegcp/github.com/lavanya55/gcpgradlespring1:$COMMIT_SHA', '.']
images: ['gcr.io/gcpgradlespring1:$COMMIT_SHA/spring-boot']
